- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 50m
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 64Mi
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 100m
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 128Mi
