apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml

commonLabels:
  app.kubernetes.io/name: file-processing-api
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: fileprocessing-system

images:
  - name: achodak/fileprocessing-api
    newTag: 37205639-c8a3-4bff-b2ff-d3c481fc28a6