apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fileprocessing-webhook-tls
  namespace: argo-events
spec:
  secretName: fileprocessing-webhook-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  ipAddresses:
  - 100.80.77.190
  usages:
  - digital signature
  - key encipherment