apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - eventbus.yaml
  - argo-events-rbac.yaml
  - webhook-eventsource.yaml
  - workflow-sensor.yaml
  - webhook-ingress.yaml

namespace: argo-events