apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: fileprocessing-dev

commonLabels:
  environment: dev

# Define all three images for replacement
images:
- name: achodak/fileprocessing-api
  newTag: 54-320ea01
- name: achodak/fileprocessing-notifier
  newTag: 54-320ea01
- name: achodak/fileprocessing-processor
  newTag: 54-320ea01

# Scale down replicas for dev environment

# Update the ingress hostname for dev

# Use smaller resource requests and limits in dev

# Add environment variables for dev
patchesJson6902:
- path: patches/scale-api-replicas.yaml
  target:
    group: apps
    kind: Deployment
    name: api
    version: v1
- path: patches/scale-processor-replicas.yaml
  target:
    group: apps
    kind: Deployment
    name: processor
    version: v1
- path: patches/scale-notifier-replicas.yaml
  target:
    group: apps
    kind: Deployment
    name: notifier
    version: v1
- path: patches/update-ingress-host.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: fileprocessing-ingress
    version: v1
- path: patches/update-api-resources.yaml
  target:
    group: apps
    kind: Deployment
    name: api
    version: v1
- path: patches/update-processor-resources.yaml
  target:
    group: apps
    kind: Deployment
    name: processor
    version: v1
- path: patches/update-notifier-resources.yaml
  target:
    group: apps
    kind: Deployment
    name: notifier
    version: v1
- path: patches/add-env-vars.yaml
  target:
    group: apps
    kind: Deployment
    name: api
    version: v1

configMapGenerator:
- literals:
  - LOG_LEVEL=debug
  - API_TIMEOUT=30s
  - RETRY_COUNT=3
  name: app-config
