apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-v2
  namespace: fileprocessing
  labels:
    app: notifier
    version: v2
    managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifier
      version: v2
  template:
    metadata:
      labels:
        app: notifier
        version: v2
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      containers:
      - name: notifier
        image: achodak/fileprocessing-notifier:latest
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: postgres-host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: postgres-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: rabbitmq-host
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: rabbitmq-user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: rabbitmq-password
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
  namespace: fileprocessing
spec:
  selector:
    app: notifier
    deployment-method: argocd
    version: v2
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP