apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileprocessing-ingress
  namespace: fileprocessing-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
    - fileprocessing.example.com
    secretName: fileprocessing-tls
  rules:
  - host: fileprocessing.example.com
    http:
      paths:
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
      - path: /upload
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
      - path: /status
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
      - path: /notifications
        pathType: Prefix
        backend:
          service:
            name: notifier-service
            port:
              number: 80
      - path: /minio
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9001
      - path: /argo
        pathType: Prefix
        backend:
          service:
            name: argo-server
            port:
              number: 2746
      - path: /fileprocessing-push
        pathType: Prefix
        backend:
          service:
            name: fileprocessing-webhook-eventsource-svc
            port:
              number: 12000