apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- nfs-pv.yaml
- postgres.yaml
- rabbitmq.yaml
- minio.yaml
- api.yaml
- processor.yaml
- notifier.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: fileprocessing
  app.kubernetes.io/managed-by: argocd