apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: achodak/fileprocessing-api
  newTag: 467ea98c-d70a-4bf5-a7c3-1f5add69ea2e
- name: achodak/fileprocessing-notifier
  newTag: 467ea98c-d70a-4bf5-a7c3-1f5add69ea2e
- name: achodak/fileprocessing-processor
  newTag: 467ea98c-d70a-4bf5-a7c3-1f5add69ea2e

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- nfs-pv.yaml
- postgres.yaml
- rabbitmq.yaml
- minio.yaml
- api.yaml
- processor.yaml
- notifier.yaml
- ingress.yaml
- storage.yaml
- workflows/workflow-template.yaml

commonLabels:
  app.kubernetes.io/part-of: fileprocessing
  app.kubernetes.io/managed-by: argocd