apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileprocessing-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exported/path
    server: nfs-server.example.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: fileprocessing
spec:
  accessModes:
    - ReadWriteMany  # Important for multiple replicas
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs