apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    app: notifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: achodak/fileprocessing-notifier:latest
        # Remove the command and args - let it use the CMD from Dockerfile
        # which is ["python", "notifier.py"]
        envFrom:
        - configMapRef:
            name: fileprocessing-config
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: postgres-host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: postgres-password
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: rabbitmq-url
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
        - name: NFS_PATH
          value: "$(NFS_MOUNT_PATH)"
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: notifier-service
spec:
  selector:
    app: notifier
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP