apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: fileprocessing-dev
  labels:
    app: processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: processor
        image: achodak/fileprocessing-processor:latest  # This will be updated by CI
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: postgres-host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: postgres-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: rabbitmq-host
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: rabbitmq-user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: rabbitmq-password
        - name: MINIO_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: minio-host
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: minio-secret-key
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: notification-service-url
        - name: NFS_PATH
          value: "/mnt/nfs_clientshare"
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: nfs-pvc-new