apiVersion: v1
kind: Secret
metadata:
  name: fileprocessing-secrets
type: Opaque
stringData:
  postgres-user: "admin"
  postgres-password: "change-me-in-production"
  rabbitmq-user: "guest"
  rabbitmq-password: "guest"
  rabbitmq-url: <base64-encoded-rabbitmq-url>
  minio-access-key: "minioadmin"
  minio-secret-key: "minioadmin"