apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: fileprocessing-webhook
  namespace: argo-events
spec:
  webhook:
    github-webhook:
      port: "12000"
      endpoint: /fileprocessing-push
      method: POST
      # Optional: Add webhook secret for security
      # webhookSecret:
      #   name: github-webhook-secret
      #   key: secret