apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fileprocessing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-org/fileprocessing-gitops.git
    targetRevision: main
    path: deploy/overlays/dev  # Points to the overlay for dev environment
  destination:
    server: https://kubernetes.default.svc
    namespace: fileprocessing-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
