apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fileprocessing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chaladak/fileprocessing-infra.git  # Fixed typo: chladak -> chaladak
    targetRevision: HEAD
    path: deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: fileprocessing-dev  # Changed from argocd to fileprocessing-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true