apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chaladak/fileprocessing-infra.git
    targetRevision: main
    path: deploy/base
    kustomize:
      namePrefix: argo-events-
      namespace: argo-events
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true