apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-and-deploy-template
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: build-and-deploy
  imagePullSecrets:
  - name: docker-credentials
  arguments:
    parameters:
    - name: docker-username
      value: "achodak"
    - name: app-git-repo
      value: "https://github.com/chaladak/fileprocessing-app.git"
    - name: infra-git-repo
      value: "https://github.com/chaladak/fileprocessing-infra.git"
    - name: infra-git-branch
      value: "main"
    - name: git-commit
      value: "latest"
    - name: git-branch
      value: "refs/heads/main"
  templates:
  - name: build-and-deploy
    steps:
    # Build all services in parallel
    - - name: build-api-service
        template: docker-build
        arguments:
          parameters:
          - name: service-path
            value: "api_service"
          - name: image-name
            value: "fileprocessing-api"
          - name: tag
            value: "{{workflow.uid}}"
      - name: build-processor-service
        template: docker-build
        arguments:
          parameters:
          - name: service-path
            value: "processor_service"
          - name: image-name
            value: "fileprocessing-processor"
          - name: tag
            value: "{{workflow.uid}}"
      - name: build-notification-service
        template: docker-build
        arguments:
          parameters:
          - name: service-path
            value: "notification_service"
          - name: image-name
            value: "fileprocessing-notifier"
          - name: tag
            value: "{{workflow.uid}}"
    # Run integration tests
    - - name: integration-tests
        template: run-integration-tests
    # Update infra repository and trigger Argo CD sync
    - - name: update-infra-and-sync
        template: update-infra
        arguments:
          parameters:
          - name: api-image
            value: "{{workflow.parameters.docker-username}}/fileprocessing-api:{{workflow.uid}}"
          - name: processor-image
            value: "{{workflow.parameters.docker-username}}/fileprocessing-processor:{{workflow.uid}}"
          - name: notifier-image
            value: "{{workflow.parameters.docker-username}}/fileprocessing-notifier:{{workflow.uid}}"
  - name: docker-build
    inputs:
      parameters:
      - name: service-path
      - name: image-name
      - name: tag
    container:
      image: docker:20.10.7-dind
      command: [sh, -c]
      env:
      - name: DOCKER_USERNAME
        value: "{{workflow.parameters.docker-username}}"
      - name: DOCKER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: docker-credentials
            key: docker-password
      - name: DOCKER_BUILDKIT
        value: "1"
      - name: BUILDKIT_PROGRESS
        value: "plain"
      args:
      - |
        set -e
        dockerd \
          --host=unix:///var/run/docker.sock \
          --default-ulimit nofile=65536:65536 \
          --max-concurrent-downloads 3 \
          --max-concurrent-uploads 3 &
        timeout=60
        while ! docker info >/dev/null 2>&1; do
          if [ $timeout -le 0 ]; then
            echo "Docker daemon failed to start"
            exit 1
          fi
          sleep 2
          timeout=$((timeout-2))
        done
        echo "Docker daemon started successfully"
        apk add --no-cache git
        echo "Cloning app repository..."
        git clone {{workflow.parameters.app-git-repo}} /workspace
        cd /workspace
        if [ "{{workflow.parameters.git-commit}}" != "latest" ]; then
          echo "Checking out commit: {{workflow.parameters.git-commit}}"
          git checkout {{workflow.parameters.git-commit}}
        fi
        if [ ! -d "./{{inputs.parameters.service-path}}" ]; then
          echo "Error: Service directory ./{{inputs.parameters.service-path}} not found"
          ls -la
          exit 1
        fi
        if [ ! -f "./{{inputs.parameters.service-path}}/Dockerfile" ]; then
          echo "Error: Dockerfile not found in ./{{inputs.parameters.service-path}}"
          ls -la ./{{inputs.parameters.service-path}}/
          exit 1
        fi
        echo "Logging into Docker Hub..."
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        echo "Building image for {{inputs.parameters.service-path}}..."
        docker build \
          --no-cache \
          --progress=plain \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t $DOCKER_USERNAME/{{inputs.parameters.image-name}}:{{inputs.parameters.tag}} \
          -t $DOCKER_USERNAME/{{inputs.parameters.image-name}}:latest \
          ./{{inputs.parameters.service-path}}
        echo "Pushing images..."
        docker push $DOCKER_USERNAME/{{inputs.parameters.image-name}}:{{inputs.parameters.tag}}
        docker push $DOCKER_USERNAME/{{inputs.parameters.image-name}}:latest
        echo "Build and push completed successfully"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "2Gi"
          cpu: "1000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
  - name: run-integration-tests
    container:
      image: docker:20.10.7
      command: [sh, -c]
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      args:
        - |
          set -e
          apk add --no-cache git python3 py3-pip docker-compose curl jq
          echo "Cloning app repository..."
          git clone {{workflow.parameters.app-git-repo}} /workspace
          cd /workspace
          if [ "{{workflow.parameters.git-commit}}" != "latest" ]; then
            echo "Checking out commit: {{workflow.parameters.git-commit}}"
            git checkout {{workflow.parameters.git-commit}}
          fi

          echo "Performing thorough cleanup..."
          # Stop and remove any running containers from previous runs
          docker-compose -f ./tests/integration/docker-compose.yml down -v --remove-orphans || true
          
          # Remove containers that might be stuck
          docker ps -aq --filter "label=com.docker.compose.project=integration" | xargs -r docker rm -f || true
          
          # Clean up Docker system
          docker container prune -f || true
          docker network prune -f || true
          docker volume prune -f || true
          docker system prune -f || true

          # Wait a moment for cleanup to complete
          sleep 5

          echo "Pulling fresh images..."
          docker pull minio/minio:latest || true
          docker pull rabbitmq:3-management || true

          echo "Starting integration test services with retry logic..."
          retry_count=0
          max_retries=3
          
          while [ $retry_count -lt $max_retries ]; do
            echo "Attempt $((retry_count + 1)) of $max_retries"
            
            if docker-compose -f ./tests/integration/docker-compose.yml up -d --force-recreate --remove-orphans; then
              echo "Services started successfully"
              break
            else
              echo "Failed to start services, attempt $((retry_count + 1))"
              retry_count=$((retry_count + 1))
              
              if [ $retry_count -lt $max_retries ]; then
                echo "Cleaning up and retrying..."
                docker-compose -f ./tests/integration/docker-compose.yml down -v --remove-orphans || true
                docker container prune -f || true
                sleep 10
              else
                echo "All retry attempts failed"
                exit 1
              fi
            fi
          done

          echo "Waiting for services to be healthy..."
          timeout=120
          elapsed=0
          interval=10
          healthy_services=0
          
          while [ $elapsed -lt $timeout ]; do
            echo "Checking service health... ($elapsed/$timeout seconds)"
            
            # Check MinIO health
            minio_healthy=0
            if curl -f http://localhost:9000/minio/health/live >/dev/null 2>&1; then
              minio_healthy=1
              echo "MinIO is healthy"
            else
              echo "MinIO not yet healthy"
            fi
            
            # Check RabbitMQ health
            rabbitmq_healthy=0
            if docker exec $(docker-compose -f ./tests/integration/docker-compose.yml ps -q rabbitmq) rabbitmqctl status >/dev/null 2>&1; then
              rabbitmq_healthy=1
              echo "RabbitMQ is healthy"
            else
              echo "RabbitMQ not yet healthy"
            fi
            
            healthy_services=$((minio_healthy + rabbitmq_healthy))
            
            if [ $healthy_services -eq 2 ]; then
              echo "All services are healthy!"
              break
            fi
            
            docker ps
            sleep $interval
            elapsed=$((elapsed + interval))
          done

          if [ $healthy_services -lt 2 ]; then
            echo "ERROR: Services failed to become healthy within $timeout seconds"
            echo "Service status:"
            docker-compose -f ./tests/integration/docker-compose.yml ps
            echo "Service logs:"
            docker-compose -f ./tests/integration/docker-compose.yml logs
            exit 1
          fi

          echo "Creating test network if it doesn't exist..."
          docker network create integration-test-network 2>/dev/null || true

          echo "Starting test container..."
          container_id=$(docker run -d \
            --network integration-test-network \
            --add-host host.docker.internal:host-gateway \
            -e TESTING=true \
            -e S3_ENDPOINT=http://host.docker.internal:9000 \
            -e S3_ACCESS_KEY=minioadmin \
            -e S3_SECRET_KEY=minioadmin \
            -e RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672/%2F \
            -e DATABASE_URL=sqlite:///:memory: \
            -e NFS_PATH=/tmp \
            -e PYTHONPATH=/app \
            python:3.12-slim \
            sleep 600)

          # Verify container is running
          if ! docker ps | grep -q $container_id; then
            echo "ERROR: Test container failed to start"
            exit 1
          fi

          docker exec $container_id mkdir -p /app /app/tests
          docker cp ./api_service/. $container_id:/app/api_service/
          docker cp ./processor_service/. $container_id:/app/processor_service/
          docker cp ./notification_service/. $container_id:/app/notification_service/
          docker cp ./tests/integration/. $container_id:/app/tests/integration/

          docker exec $container_id touch /app/api_service/__init__.py
          docker exec $container_id touch /app/processor_service/__init__.py
          docker exec $container_id touch /app/notification_service/__init__.py

          echo "Installing test dependencies..."
          docker exec $container_id /bin/bash -c "
            set -e
            apt-get update && apt-get install -y curl netcat-openbsd
            pip install --no-cache-dir -r tests/integration/requirements.txt
            pip install --no-cache-dir -r api_service/requirements.txt
            pip install --no-cache-dir -r processor_service/requirements.txt
            pip install --no-cache-dir -r notification_service/requirements.txt
          "

          echo "Verifying connectivity from test container..."
          docker exec $container_id /bin/bash -c "
            echo 'Testing MinIO connectivity...'
            curl -f http://host.docker.internal:9000/minio/health/live || exit 1
            echo 'Testing RabbitMQ connectivity...'
            nc -zv host.docker.internal 5672 || exit 1
          "

          echo "Running integration tests..."
          docker exec $container_id /bin/bash -c "
            set -e
            cd /app
            export PYTHONPATH=/app:/app/api_service:/app/processor_service:/app/notification_service:\$PYTHONPATH
            python -m pytest tests/integration/test_integration.py -v --tb=short
          "

          test_exit_code=$?

          echo "Cleaning up test containers..."
          docker rm -f $container_id || true
          docker network rm integration-test-network || true
          docker-compose -f ./tests/integration/docker-compose.yml down -v

          if [ $test_exit_code -eq 0 ]; then
            echo "Integration tests PASSED"
          else
            echo "Integration tests FAILED"
            exit $test_exit_code
          fi
    volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
  - name: update-infra
    inputs:
      parameters:
      - name: api-image
      - name: processor-image
      - name: notifier-image
    container:
      image: alpine/git:2.36.2
      command: [sh, -c]
      env:
      - name: GIT_USERNAME
        value: "{{workflow.parameters.docker-username}}"
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            name: git-credentials
            key: git-token
      args:
      - |
        set -e
        git config --global user.name "Argo Workflow"
        git config --global user.email "argo@workflow.com"
        echo "Cloning infra repository..."
        git clone https://$GIT_USERNAME:$GIT_TOKEN@github.com/chaladak/fileprocessing-infra.git /fileprocessing-infra
        cd /fileprocessing-infra
        git checkout {{workflow.parameters.infra-git-branch}}
        API_TAG=$(echo "{{inputs.parameters.api-image}}" | sed 's|.*:||')
        PROCESSOR_TAG=$(echo "{{inputs.parameters.processor-image}}" | sed 's|.*:||')
        NOTIFIER_TAG=$(echo "{{inputs.parameters.notifier-image}}" | sed 's|.*:||')
        echo "Updating image tags in kustomization.yaml..."
        sed -i "/name: achodak\/fileprocessing-api/,/newTag:/ s|newTag: .*|newTag: $API_TAG|" deploy/overlays/dev/kustomization.yaml
        sed -i "/name: achodak\/fileprocessing-notifier/,/newTag:/ s|newTag: .*|newTag: $NOTIFIER_TAG|" deploy/overlays/dev/kustomization.yaml
        sed -i "/name: achodak\/fileprocessing-processor/,/newTag:/ s|newTag: .*|newTag: $PROCESSOR_TAG|" deploy/overlays/dev/kustomization.yaml
        git add .
        git commit -m "Update image tags to {{workflow.uid}} - triggered by commit {{workflow.parameters.git-commit}}"
        git push origin {{workflow.parameters.infra-git-branch}}