apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-and-deploy-template
  namespace: argo
spec:
  serviceAccountName: argo
  entrypoint: build-and-deploy
  imagePullSecrets:
  - name: docker-credentials
  arguments:
    parameters:
    - name: docker-username
      value: "achodak"
    - name: app-git-repo
      value: "https://github.com/chaladak/fileprocessing-app.git"
    - name: infra-git-repo
      value: "https://github.com/chaladak/fileprocessing-infra.git"
    - name: infra-git-branch
      value: "main"
    - name: git-commit
      value: "latest"
    - name: git-branch
      value: "refs/heads/main"
  templates:
  - name: build-and-deploy
    steps:
    - - name: build-api-service
        template: docker-build
        arguments:
          parameters:
          - name: service-path
            value: "api_service"
          - name: image-name
            value: "fileprocessing-api"
          - name: tag
            value: "{{workflow.uid}}"
      - name: build-processor-service
        template: docker-build
        arguments:
          parameters:
          - name: service-path
            value: "processor_service"
          - name: image-name
            value: "fileprocessing-processor"
          - name: tag
            value: "{{workflow.uid}}"
      - name: build-notification-service
        template: docker-build
        arguments:
          parameters:
          - name: service-path
            value: "notification_service"
          - name: image-name
            value: "fileprocessing-notifier"
          - name: tag
            value: "{{workflow.uid}}"
    - - name: integration-tests
        template: run-integration-tests
    - - name: update-infra-and-sync
        template: update-infra
        arguments:
          parameters:
          - name: api-image
            value: "{{workflow.parameters.docker-username}}/fileprocessing-api:{{workflow.uid}}"
          - name: processor-image
            value: "{{workflow.parameters.docker-username}}/fileprocessing-processor:{{workflow.uid}}"
          - name: notifier-image
            value: "{{workflow.parameters.docker-username}}/fileprocessing-notifier:{{workflow.uid}}"
  
  - name: docker-build
    inputs:
      parameters:
      - name: service-path
      - name: image-name
      - name: tag
    container:
      image: docker:20.10.7-dind
      command: [sh, -c]
      env:
      - name: DOCKER_USERNAME
        value: "{{workflow.parameters.docker-username}}"
      - name: DOCKER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: docker-credentials
            key: docker-password
      - name: DOCKER_BUILDKIT
        value: "1"
      - name: BUILDKIT_PROGRESS
        value: "plain"
      args:
      - |
        set -e
        dockerd \
          --host=unix:///var/run/docker.sock \
          --default-ulimit nofile=65536:65536 \
          --max-concurrent-downloads 3 \
          --max-concurrent-uploads 3 &
        timeout=60
        while ! docker info >/dev/null 2>&1; do
          if [ $timeout -le 0 ]; then
            echo "Docker daemon failed to start"
            exit 1
          fi
          sleep 2
          timeout=$((timeout-2))
        done
        echo "Docker daemon started successfully"
        apk add --no-cache git
        echo "Cloning app repository..."
        git clone {{workflow.parameters.app-git-repo}} /workspace
        cd /workspace
        if [ "{{workflow.parameters.git-commit}}" != "latest" ]; then
          echo "Checking out commit: {{workflow.parameters.git-commit}}"
          git checkout {{workflow.parameters.git-commit}}
        fi
        if [ ! -d "./{{inputs.parameters.service-path}}" ]; then
          echo "Error: Service directory ./{{inputs.parameters.service-path}} not found"
          ls -la
          exit 1
        fi
        if [ ! -f "./{{inputs.parameters.service-path}}/Dockerfile" ]; then
          echo "Error: Dockerfile not found in ./{{inputs.parameters.service-path}}"
          ls -la ./{{inputs.parameters.service-path}}/
          exit 1
        fi
        echo "Logging into Docker Hub..."
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        echo "Building image for {{inputs.parameters.service-path}}..."
        docker build \
          --no-cache \
          --progress=plain \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t $DOCKER_USERNAME/{{inputs.parameters.image-name}}:{{inputs.parameters.tag}} \
          -t $DOCKER_USERNAME/{{inputs.parameters.image-name}}:latest \
          ./{{inputs.parameters.service-path}}
        echo "Pushing images..."
        docker push $DOCKER_USERNAME/{{inputs.parameters.image-name}}:{{inputs.parameters.tag}}
        docker push $DOCKER_USERNAME/{{inputs.parameters.image-name}}:latest
        echo "Build and push completed successfully"
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "2Gi"
          cpu: "1000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
  - name: run-integration-tests
    container:
      image: docker:20.10.7
      command: [sh, -c]
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      args:
        - |
          set -e
          apk add --no-cache git python3 py3-pip docker-compose curl
          echo "Cloning app repository..."
          git clone {{workflow.parameters.app-git-repo}} /workspace
          cd /workspace
          if [ "{{workflow.parameters.git-commit}}" != "latest" ]; then
            echo "Checking out commit: {{workflow.parameters.git-commit}}"
            git checkout {{workflow.parameters.git-commit}}
          fi

          echo "Cleaning up any existing containers and networks..."
          docker-compose -f ./tests/integration/docker-compose.yml down -v --remove-orphans || true
          docker container prune -f || true
          docker network prune -f || true
          docker volume prune -f || true

          echo "Starting integration test services..."
          docker-compose -f ./tests/integration/docker-compose.yml up -d --force-recreate

          echo "Waiting for services to be healthy..."
          timeout=100
          elapsed=0
          interval=5
          while [ $elapsed -lt $timeout ]; do
            if docker-compose -f ./tests/integration/docker-compose.yml ps | grep -q "healthy"; then
              health_count=$(docker-compose -f ./tests/integration/docker-compose.yml ps | grep -c "healthy" || echo "0")
              if [ "$health_count" -ge "2" ]; then
                echo "Services are healthy!"
                break
              fi
            fi
            echo "Waiting for services to be healthy... ($elapsed/$timeout seconds)"
            sleep $interval
            elapsed=$((elapsed + interval))
          done

          if [ $elapsed -ge $timeout ]; then
            echo "ERROR: Services failed to become healthy within $timeout seconds"
            docker-compose -f ./tests/integration/docker-compose.yml ps
            docker-compose -f ./tests/integration/docker-compose.yml logs
            exit 1
          fi

          echo "Starting test container..."
          container_id=$(docker run -d \
            --network host \
            -e TESTING=true \
            -e S3_ENDPOINT=http://localhost:9000 \
            -e S3_ACCESS_KEY=minioadmin \
            -e S3_SECRET_KEY=minioadmin \
            -e RABBITMQ_URL=amqp://guest:guest@localhost:5672/%2F \
            -e DATABASE_URL=sqlite:///:memory: \
            -e NFS_PATH=/tmp \
            -e PYTHONPATH=/app \
            python:3.12-slim \
            sleep 600)

          docker exec $container_id mkdir -p /app /app/tests
          docker cp ./api_service/. $container_id:/app/api_service/
          docker cp ./processor_service/. $container_id:/app/processor_service/
          docker cp ./notification_service/. $container_id:/app/notification_service/
          docker cp ./tests/integration/. $container_id:/app/tests/integration/

          docker exec $container_id touch /app/api_service/__init__.py
          docker exec $container_id touch /app/processor_service/__init__.py
          docker exec $container_id touch /app/notification_service/__init__.py

          echo "Running integration tests..."
          docker exec $container_id /bin/bash -c "
            set -e
            cd /app
            pip install --no-cache-dir -r tests/integration/requirements.txt
            pip install --no-cache-dir -r api_service/requirements.txt
            pip install --no-cache-dir -r processor_service/requirements.txt
            pip install --no-cache-dir -r notification_service/requirements.txt
            export PYTHONPATH=/app:/app/api_service:/app/processor_service:/app/notification_service:\$PYTHONPATH
            python -m pytest tests/integration/test_integration.py -v --tb=short
          "

          test_exit_code=$?

          echo "Cleaning up test containers..."
          docker rm -f $container_id
          docker-compose -f ./tests/integration/docker-compose.yml down -v

          if [ $test_exit_code -eq 0 ]; then
            echo "Integration tests PASSED"
          else
            echo "Integration tests FAILED"
            exit $test_exit_code
          fi
    volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"
  - name: update-infra
    inputs:
      parameters:
      - name: api-image
      - name: processor-image
      - name: notifier-image
    container:
      image: alpine/git:2.36.2
      command: [sh, -c]
      env:
      - name: GIT_USERNAME
        value: "{{workflow.parameters.docker-username}}"
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            name: git-credentials
            key: git-token
      args:
      - |
        set -e
        git config --global user.name "Argo Workflow"
        git config --global user.email "argo@workflow.com"
        echo "Cloning infra repository..."
        git clone https://$GIT_USERNAME:$GIT_TOKEN@github.com/chaladak/fileprocessing-infra.git /fileprocessing-infra
        cd /fileprocessing-infra
        git checkout {{workflow.parameters.infra-git-branch}}
        API_TAG=$(echo "{{inputs.parameters.api-image}}" | sed 's|.*:||')
        PROCESSOR_TAG=$(echo "{{inputs.parameters.processor-image}}" | sed 's|.*:||')
        NOTIFIER_TAG=$(echo "{{inputs.parameters.notifier-image}}" | sed 's|.*:||')
        echo "Updating image tags in kustomization.yaml..."
        sed -i "/name: achodak\/fileprocessing-api/,/newTag:/ s|newTag: .*|newTag: $API_TAG|" deploy/overlays/dev/kustomization.yaml
        sed -i "/name: achodak\/fileprocessing-notifier/,/newTag:/ s|newTag: .*|newTag: $NOTIFIER_TAG|" deploy/overlays/dev/kustomization.yaml
        sed -i "/name: achodak\/fileprocessing-processor/,/newTag:/ s|newTag: .*|newTag: $PROCESSOR_TAG|" deploy/overlays/dev/kustomization.yaml
        git add .
        git commit -m "Update image tags to {{workflow.uid}} - triggered by commit {{workflow.parameters.git-commit}}"
        git push origin {{workflow.parameters.infra-git-branch}}