apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notifier
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaladak/fileprocessing-infra.git
    targetRevision: HEAD
    path: manifests/notifier
  destination:
    server: https://kubernetes.default.svc
    namespace: fileprocessing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true