# Argo Workflows templates
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chaladak/fileprocessing-infra.git
    targetRevision: HEAD
    path: manifests/workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: fileprocessing-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  syncWaves:
    - order: 2