apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - storage.yaml
  - nfs-pv.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - minio.yaml
  - ingress.yaml

# Add labels to all resources
labels:
  - pairs:
      app.kubernetes.io/name: fileprocessing
      app.kubernetes.io/component: infrastructure
      app.kubernetes.io/part-of: fileprocessing-system