apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - storage.yaml
  - nfs-pv.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - minio.yaml
  - ingress.yaml

# Add labels to all resources
labels:
  - pairs:
      app.kubernetes.io/name: fileprocessing
      app.kubernetes.io/component: infrastructure
      app.kubernetes.io/part-of: fileprocessing-system

# Use 'patches' with correct resource targets
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: fileprocessing-dev
        annotations:
          argocd.argoproj.io/sync-wave: "-2"
    target:
      kind: Namespace
      name: fileprocessing-dev
  
  - patch: |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: local-storage
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    target:
      kind: StorageClass
      name: local-storage
    
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "-1"
    target:
      kind: Secret
      name: fileprocessing-secrets
  
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "-1"
    target:
      kind: ConfigMap
      name: fileprocessing-config
  
  # Minio PV
  - patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "0"
    target:
      kind: PersistentVolume
      name: minio-pv
  
  # Other PVs (adjust name as needed)
  - patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "0"
    target:
      kind: PersistentVolume
      name: fileprocessing-pv-new
  
  # Minio PVC
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "0"
    target:
      kind: PersistentVolumeClaim
      name: minio-pvc
  
  # Postgres Deployment
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "1"
    target:
      kind: Deployment
      name: postgres
  
  # RabbitMQ Deployment
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "1"
    target:
      kind: Deployment
      name: rabbitmq
  
  # Minio Deployment (correct name)
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          argocd.argoproj.io/sync-wave: "1"
    target:
      kind: Deployment
      name: minio