apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: shared-storage
    type: nfs
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage-class
  nfs:
    path: /srv/nfs/share
    server: 100.80.77.189

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: fileprocessing
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage-class
  selector:
    matchLabels:
      app: shared-storage
      type: nfs