apiVersion: v1
kind: Secret
metadata:
  name: fileprocessing-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  postgres-user: "admin"
  postgres-password: "change-me-in-production"
  rabbitmq-user: "guest"
  rabbitmq-password: "guest"
  rabbitmq-url: amqp://guest:guest@rabbitmq-service.fileprocessing-dev.svc.cluster.local:5672/
  minio-access-key: "minioadmin"
  minio-secret-key: "minioadmin"