apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: achodak/fileprocessing-api:latest  # This will be updated by CI
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: postgres-host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: postgres-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: postgres-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: rabbitmq-host
        - name: MINIO_HOST
          valueFrom:
            configMapKeyRef:
              name: fileprocessing-config
              key: minio-host
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fileprocessing-secrets
              key: minio-secret-key
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: fileprocessing-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP