apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileprocessing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - fileprocessing.example.com
    secretName: fileprocessing-tls
  rules:
  - host: fileprocessing.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
      - path: /notifications
        pathType: Prefix
        backend:
          service:
            name: notifier-service
            port:
              number: 80
      - path: /minio
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9001  # minio console